# Generated by Django 3.2.16 on 2023-08-18 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='max_percentage',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='min_percentage',
        ),
        migrations.RemoveField(
            model_name='reciperawmaterial',
            name='percentage',
        ),
        migrations.AddField(
            model_name='reciperawmaterial',
            name='max_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='最大占比 (%)'),
        ),
        migrations.AddField(
            model_name='reciperawmaterial',
            name='min_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='最小占比 (%)'),
        ),
    ]
