# Generated by Django 3.2.16 on 2023-08-18 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20230818_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMaterialElementContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_content', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='含量 (%)')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.element')),
                ('recipe_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.reciperawmaterial')),
            ],
            options={
                'verbose_name': '配方材料元素含量',
                'verbose_name_plural': '配方材料元素含量',
                'unique_together': {('recipe_material', 'element')},
            },
        ),
    ]
