# Generated by Django 3.2.16 on 2023-08-18 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_element_recipematerialelementcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipematerialelementcontent',
            options={'verbose_name': 'Recipe Material Element Content', 'verbose_name_plural': 'Recipe Material Element Contents'},
        ),
        migrations.AlterField(
            model_name='recipematerialelementcontent',
            name='percentage_content',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Content Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='reciperawmaterial',
            name='max_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='reciperawmaterial',
            name='max_weight_kg_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Max Weight (kg/ton)'),
        ),
        migrations.AlterField(
            model_name='reciperawmaterial',
            name='min_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Min Percentage (%)'),
        ),
        migrations.AlterField(
            model_name='reciperawmaterial',
            name='min_weight_kg_per_ton',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Min Weight (kg/ton)'),
        ),
    ]
