# Generated by Django 3.2.16 on 2023-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20230818_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialattribute',
            name='data_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('color', 'Color'), ('text', 'Text')], default='numeric', max_length=20),
        ),
        migrations.AlterField(
            model_name='materialattributevalue',
            name='value',
            field=models.TextField(),
        ),
    ]
