# Generated by Django 3.2.16 on 2023-08-18 15:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20230818_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAttributeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.materialattribute')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMaterialAttributeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Min Percentage (%)')),
                ('max_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Max Percentage (%)')),
                ('attribute_limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.materialattributelimit')),
                ('recipe_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.reciperawmaterial')),
            ],
            options={
                'verbose_name': 'Recipe Material Attribute Limit',
                'verbose_name_plural': 'Recipe Material Attribute Limits',
                'unique_together': {('recipe_material', 'attribute_limit')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='recipematerialelementcontent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recipematerialelementcontent',
            name='element',
        ),
        migrations.RemoveField(
            model_name='recipematerialelementcontent',
            name='recipe_material',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='RecipeMaterialElementContent',
        ),
    ]
