# Generated by Django 3.2.16 on 2023-08-18 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_auto_20230819_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperawmaterial',
            name='max_weight_kg_per_ton',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Max Weight (kg/ton)'),
        ),
        migrations.AlterField(
            model_name='reciperawmaterial',
            name='min_weight_kg_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Min Weight (kg/ton)'),
        ),
    ]
