# Generated by Django 3.2.16 on 2023-08-18 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_auto_20230819_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipematerialattributelimit',
            name='max_value',
            field=models.DecimalField(decimal_places=10, default=999.9, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Value'),
        ),
        migrations.AddField(
            model_name='recipematerialattributelimit',
            name='min_value',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min Value'),
        ),
        migrations.AddField(
            model_name='recipematerialattributelimit',
            name='raw_material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.rawmaterial'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recipematerialattributelimit',
            unique_together={('raw_material', 'attribute_limit')},
        ),
        migrations.RemoveField(
            model_name='recipematerialattributelimit',
            name='max_percentage',
        ),
        migrations.RemoveField(
            model_name='recipematerialattributelimit',
            name='min_percentage',
        ),
        migrations.RemoveField(
            model_name='recipematerialattributelimit',
            name='recipe_material',
        ),
    ]
