# Generated by Django 3.2.16 on 2023-08-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_auto_20230819_0229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeMaterialAttributeLimit',
            new_name='RecipeAttributeLimit',
        ),
        migrations.AlterModelOptions(
            name='recipeattributelimit',
            options={'verbose_name': 'Recipe Attribute Limit', 'verbose_name_plural': 'Recipe Attribute Limits'},
        ),
        migrations.AddField(
            model_name='recipeattributelimit',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.materialattribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeattributelimit',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredients.recipe'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recipeattributelimit',
            unique_together={('recipe', 'attribute')},
        ),
        migrations.RemoveField(
            model_name='recipeattributelimit',
            name='attribute_limit',
        ),
        migrations.RemoveField(
            model_name='recipeattributelimit',
            name='raw_material',
        ),
    ]
